create table warehouse
(
    product_name varchar,
    can_be_use   boolean
);

create table products
(
    unique_code  integer generated by default as identity
        constraint products_pk
            primary key,
    product_name varchar,
    size         varchar,
    count        integer
);

INSERT INTO public.products (unique_code, product_name, size, count) VALUES (1, 'milk', '0.2m', 15);
INSERT INTO public.products (unique_code, product_name, size, count) VALUES (2, 'tables', '1.5m', 20);
INSERT INTO public.products (unique_code, product_name, size, count) VALUES (3, 'doors', '1.8m', 18);
INSERT INTO public.products (unique_code, product_name, size, count) VALUES (4, 'microphones', '0.15m', 4);



